# Generated by Django 6.1 on 2026-08-15 05:04

import django.db.models.deletion
import django.utils.timezone
import issues.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CivicIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(default=issues.models.generate_tracking_code, max_length=20, unique=True)),
                ('reporter_name', models.CharField(blank=True, default='Concerned Resident', max_length=120)),
                ('reporter_contact', models.CharField(blank=True, max_length=60)),
                ('issue_category', models.CharField(choices=[('pothole', 'Potholes / Road Damage'), ('water', 'Water Supply Problems'), ('waste', 'Waste Management')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='issues/%Y/%m/')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, help_text='e.g. Near College Main Gate, Sector 4', max_length=255)),
                ('road_condition', models.CharField(blank=True, choices=[('Small damage', 'Small damage'), ('Moderate damage', 'Moderate damage'), ('Large pothole', 'Large pothole'), ('Multiple potholes', 'Multiple potholes'), ('Severe road damage', 'Severe road damage')], max_length=60, null=True)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=30)),
                ('water_problem_type', models.CharField(blank=True, choices=[('No water supply', 'No water supply'), ('Low water pressure', 'Low water pressure'), ('Water leakage', 'Water leakage'), ('Irregular supply', 'Irregular supply'), ('Pipeline damage', 'Pipeline damage'), ('Other', 'Other')], max_length=60, null=True)),
                ('water_duration', models.CharField(blank=True, choices=[('Less than 6 hours', 'Less than 6 hours'), ('6–12 hours', '6–12 hours'), ('12–24 hours', '12–24 hours'), ('1–3 days', '1–3 days'), ('More than 3 days', 'More than 3 days')], max_length=60, null=True)),
                ('affected_households', models.CharField(blank=True, choices=[('My household', 'My household'), ('Few nearby households', 'Few nearby households'), ('Many households', 'Many households'), ('Large community', 'Large community')], max_length=60, null=True)),
                ('waste_type', models.CharField(blank=True, choices=[('Household waste', 'Household waste'), ('Plastic waste', 'Plastic waste'), ('Construction waste', 'Construction waste'), ('Overflowing bin', 'Overflowing bin'), ('Mixed waste', 'Mixed waste'), ('Other', 'Other')], max_length=60, null=True)),
                ('waste_accumulation', models.CharField(blank=True, choices=[('Small', 'Small'), ('Moderate', 'Moderate'), ('Large', 'Large'), ('Severe', 'Severe')], max_length=60, null=True)),
                ('waste_duration', models.CharField(blank=True, choices=[('Today', 'Today'), ('1–2 days', '1–2 days'), ('3–7 days', '3–7 days'), ('More than a week', 'More than a week')], max_length=60, null=True)),
                ('issue_type', models.CharField(blank=True, default='General Civic Issue', max_length=120)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=30)),
                ('safety_risk', models.CharField(blank=True, max_length=255)),
                ('impact', models.CharField(blank=True, max_length=255)),
                ('ai_summary', models.TextField(blank=True)),
                ('recommended_department', models.CharField(blank=True, max_length=120)),
                ('recommended_action', models.TextField(blank=True)),
                ('ai_available', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Submitted', max_length=30)),
                ('assigned_department', models.CharField(blank=True, choices=[('Road Maintenance', 'Road Maintenance'), ('Water Supply Department', 'Water Supply Department'), ('Waste Management', 'Waste Management')], max_length=120)),
                ('admin_action', models.TextField(blank=True)),
                ('resolution_image', models.ImageField(blank=True, null=True, upload_to='resolutions/%Y/%m/')),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['issue_category'], name='issues_civi_issue_c_cae080_idx'), models.Index(fields=['status'], name='issues_civi_status_16b803_idx'), models.Index(fields=['priority'], name='issues_civi_priorit_1fb51d_idx'), models.Index(fields=['created_at'], name='issues_civi_created_df5cdd_idx'), models.Index(fields=['latitude', 'longitude'], name='issues_civi_latitud_0af606_idx')],
            },
        ),
    ]
